package wimbledon.modelo;
// Generated 15/11/2018 09:04:19 PM by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Cancha generated by hbm2java
 */
@Entity
@Table(name = "cancha", schema = "public")
public class Cancha implements java.io.Serializable {

	private long idcancha;
	private Tipocancha tipocancha;
	private String nombre;
	private boolean disponible;
	private Set<Reservacancha> reservacanchas = new HashSet<Reservacancha>(0);
	private Set<Partido> partidos = new HashSet<Partido>(0);

	public Cancha() {
	}

	public Cancha(long idcancha, String nombre, boolean disponible) {
		this.idcancha = idcancha;
		this.nombre = nombre;
		this.disponible = disponible;
	}

	public Cancha(long idcancha, Tipocancha tipocancha, String nombre, boolean disponible,
			Set<Reservacancha> reservacanchas, Set<Partido> partidos) {
		this.idcancha = idcancha;
		this.tipocancha = tipocancha;
		this.nombre = nombre;
		this.disponible = disponible;
		this.reservacanchas = reservacanchas;
		this.partidos = partidos;
	}

	@Id

	@Column(name = "idcancha", unique = true, nullable = false)
	public long getIdcancha() {
		return this.idcancha;
	}

	public void setIdcancha(long idcancha) {
		this.idcancha = idcancha;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "tipo")
	public Tipocancha getTipocancha() {
		return this.tipocancha;
	}

	public void setTipocancha(Tipocancha tipocancha) {
		this.tipocancha = tipocancha;
	}

	@Column(name = "nombre", nullable = false, length = 30)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "disponible", nullable = false)
	public boolean isDisponible() {
		return this.disponible;
	}

	public void setDisponible(boolean disponible) {
		this.disponible = disponible;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cancha")
	public Set<Reservacancha> getReservacanchas() {
		return this.reservacanchas;
	}

	public void setReservacanchas(Set<Reservacancha> reservacanchas) {
		this.reservacanchas = reservacanchas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cancha")
	public Set<Partido> getPartidos() {
		return this.partidos;
	}

	public void setPartidos(Set<Partido> partidos) {
		this.partidos = partidos;
	}

}
