package wimbledon.modelo;
// Generated 15/11/2018 09:04:19 PM by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Draw generated by hbm2java
 */
@Entity
@Table(name = "draw", schema = "public")
public class Draw implements java.io.Serializable {

	private long iddraw;
	private Tipodraw tipodraw;
	private Torneo torneo;
	private Set<Ronda> rondas = new HashSet<Ronda>(0);
	private Set<Drawintegrantes> drawintegranteses = new HashSet<Drawintegrantes>(0);
	private Set<Partido> partidos = new HashSet<Partido>(0);

	public Draw() {
	}

	public Draw(long iddraw) {
		this.iddraw = iddraw;
	}

	public Draw(long iddraw, Tipodraw tipodraw, Torneo torneo, Set<Ronda> rondas,
			Set<Drawintegrantes> drawintegranteses, Set<Partido> partidos) {
		this.iddraw = iddraw;
		this.tipodraw = tipodraw;
		this.torneo = torneo;
		this.rondas = rondas;
		this.drawintegranteses = drawintegranteses;
		this.partidos = partidos;
	}

	@Id

	@Column(name = "iddraw", unique = true, nullable = false)
	public long getIddraw() {
		return this.iddraw;
	}

	public void setIddraw(long iddraw) {
		this.iddraw = iddraw;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "tipo")
	public Tipodraw getTipodraw() {
		return this.tipodraw;
	}

	public void setTipodraw(Tipodraw tipodraw) {
		this.tipodraw = tipodraw;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "torneo")
	public Torneo getTorneo() {
		return this.torneo;
	}

	public void setTorneo(Torneo torneo) {
		this.torneo = torneo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "draw")
	public Set<Ronda> getRondas() {
		return this.rondas;
	}

	public void setRondas(Set<Ronda> rondas) {
		this.rondas = rondas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "draw")
	public Set<Drawintegrantes> getDrawintegranteses() {
		return this.drawintegranteses;
	}

	public void setDrawintegranteses(Set<Drawintegrantes> drawintegranteses) {
		this.drawintegranteses = drawintegranteses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "draw")
	public Set<Partido> getPartidos() {
		return this.partidos;
	}

	public void setPartidos(Set<Partido> partidos) {
		this.partidos = partidos;
	}

}
