package wimbledon.modelo;
// Generated 15/11/2018 09:04:19 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Reservacancha generated by hbm2java
 */
@Entity
@Table(name = "reservacancha", schema = "public")
public class Reservacancha implements java.io.Serializable {

	private long idreservacancha;
	private Cancha cancha;
	private Partido partido;
	private Date fechainicio;
	private Date fechafin;

	public Reservacancha() {
	}

	public Reservacancha(long idreservacancha, Date fechainicio, Date fechafin) {
		this.idreservacancha = idreservacancha;
		this.fechainicio = fechainicio;
		this.fechafin = fechafin;
	}

	public Reservacancha(long idreservacancha, Cancha cancha, Partido partido, Date fechainicio, Date fechafin) {
		this.idreservacancha = idreservacancha;
		this.cancha = cancha;
		this.partido = partido;
		this.fechainicio = fechainicio;
		this.fechafin = fechafin;
	}

	@Id

	@Column(name = "idreservacancha", unique = true, nullable = false)
	public long getIdreservacancha() {
		return this.idreservacancha;
	}

	public void setIdreservacancha(long idreservacancha) {
		this.idreservacancha = idreservacancha;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cancha")
	public Cancha getCancha() {
		return this.cancha;
	}

	public void setCancha(Cancha cancha) {
		this.cancha = cancha;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "partido")
	public Partido getPartido() {
		return this.partido;
	}

	public void setPartido(Partido partido) {
		this.partido = partido;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fechainicio", nullable = false, length = 29)
	public Date getFechainicio() {
		return this.fechainicio;
	}

	public void setFechainicio(Date fechainicio) {
		this.fechainicio = fechainicio;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fechafin", nullable = false, length = 29)
	public Date getFechafin() {
		return this.fechafin;
	}

	public void setFechafin(Date fechafin) {
		this.fechafin = fechafin;
	}

}
