package wimbledon.modelo;
// Generated 15/11/2018 09:04:19 PM by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Tipousuario generated by hbm2java
 */
@Entity
@Table(name = "tipousuario", schema = "public")
public class Tipousuario implements java.io.Serializable {

	private long idtipousuario;
	private String tipousuario;
	private Set<Usuario> usuarios = new HashSet<Usuario>(0);

	public Tipousuario() {
	}

	public Tipousuario(long idtipousuario, String tipousuario) {
		this.idtipousuario = idtipousuario;
		this.tipousuario = tipousuario;
	}

	public Tipousuario(long idtipousuario, String tipousuario, Set<Usuario> usuarios) {
		this.idtipousuario = idtipousuario;
		this.tipousuario = tipousuario;
		this.usuarios = usuarios;
	}

	@Id

	@Column(name = "idtipousuario", unique = true, nullable = false)
	public long getIdtipousuario() {
		return this.idtipousuario;
	}

	public void setIdtipousuario(long idtipousuario) {
		this.idtipousuario = idtipousuario;
	}

	@Column(name = "tipousuario", nullable = false, length = 20)
	public String getTipousuario() {
		return this.tipousuario;
	}

	public void setTipousuario(String tipousuario) {
		this.tipousuario = tipousuario;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipousuario")
	public Set<Usuario> getUsuarios() {
		return this.usuarios;
	}

	public void setUsuarios(Set<Usuario> usuarios) {
		this.usuarios = usuarios;
	}

}
