package wimbledon.modelo;
// Generated 15/11/2018 09:04:19 PM by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Tipocancha generated by hbm2java
 */
@Entity
@Table(name = "tipocancha", schema = "public")
public class Tipocancha implements java.io.Serializable {

	private long idtipocancha;
	private String tipo;
	private Set<Cancha> canchas = new HashSet<Cancha>(0);

	public Tipocancha() {
	}

	public Tipocancha(long idtipocancha, String tipo) {
		this.idtipocancha = idtipocancha;
		this.tipo = tipo;
	}

	public Tipocancha(long idtipocancha, String tipo, Set<Cancha> canchas) {
		this.idtipocancha = idtipocancha;
		this.tipo = tipo;
		this.canchas = canchas;
	}

	@Id

	@Column(name = "idtipocancha", unique = true, nullable = false)
	public long getIdtipocancha() {
		return this.idtipocancha;
	}

	public void setIdtipocancha(long idtipocancha) {
		this.idtipocancha = idtipocancha;
	}

	@Column(name = "tipo", nullable = false, length = 20)
	public String getTipo() {
		return this.tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipocancha")
	public Set<Cancha> getCanchas() {
		return this.canchas;
	}

	public void setCanchas(Set<Cancha> canchas) {
		this.canchas = canchas;
	}

}
