package wimbledon.modelo;
// Generated 15/11/2018 09:04:19 PM by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Torneo generated by hbm2java
 */
@Entity
@Table(name = "torneo", schema = "public")
public class Torneo implements java.io.Serializable {

	private long idtorneo;
	private String anio;
	private Set<Draw> draws = new HashSet<Draw>(0);

	public Torneo() {
	}

	public Torneo(long idtorneo, String anio) {
		this.idtorneo = idtorneo;
		this.anio = anio;
	}

	public Torneo(long idtorneo, String anio, Set<Draw> draws) {
		this.idtorneo = idtorneo;
		this.anio = anio;
		this.draws = draws;
	}

	@Id

	@Column(name = "idtorneo", unique = true, nullable = false)
	public long getIdtorneo() {
		return this.idtorneo;
	}

	public void setIdtorneo(long idtorneo) {
		this.idtorneo = idtorneo;
	}

	@Column(name = "anio", nullable = false, length = 4)
	public String getAnio() {
		return this.anio;
	}

	public void setAnio(String anio) {
		this.anio = anio;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "torneo")
	public Set<Draw> getDraws() {
		return this.draws;
	}

	public void setDraws(Set<Draw> draws) {
		this.draws = draws;
	}

}
