package wimbledon.modelo;
// Generated 15/11/2018 09:04:19 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(name = "usuario", schema = "public")
public class Usuario implements java.io.Serializable {

	private long idusuario;
	private Tipousuario tipousuario;
	private String nombre;
	private String apellido;
	private String login;
	private String contrasena;

	public Usuario() {
	}

	public Usuario(long idusuario, String nombre, String apellido, String login, String contrasena) {
		this.idusuario = idusuario;
		this.nombre = nombre;
		this.apellido = apellido;
		this.login = login;
		this.contrasena = contrasena;
	}

	public Usuario(long idusuario, Tipousuario tipousuario, String nombre, String apellido, String login,
			String contrasena) {
		this.idusuario = idusuario;
		this.tipousuario = tipousuario;
		this.nombre = nombre;
		this.apellido = apellido;
		this.login = login;
		this.contrasena = contrasena;
	}

	@Id

	@Column(name = "idusuario", unique = true, nullable = false)
	public long getIdusuario() {
		return this.idusuario;
	}

	public void setIdusuario(long idusuario) {
		this.idusuario = idusuario;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "tipo")
	public Tipousuario getTipousuario() {
		return this.tipousuario;
	}

	public void setTipousuario(Tipousuario tipousuario) {
		this.tipousuario = tipousuario;
	}

	@Column(name = "nombre", nullable = false, length = 30)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "apellido", nullable = false, length = 30)
	public String getApellido() {
		return this.apellido;
	}

	public void setApellido(String apellido) {
		this.apellido = apellido;
	}

	@Column(name = "login", nullable = false, length = 15)
	public String getLogin() {
		return this.login;
	}

	public void setLogin(String login) {
		this.login = login;
	}

	@Column(name = "contrasena", nullable = false, length = 30)
	public String getContrasena() {
		return this.contrasena;
	}

	public void setContrasena(String contrasena) {
		this.contrasena = contrasena;
	}

}
